name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Mirror to Hugging Face Space
        uses: huggingface/hub-sync@v0.1.0
        with:
          github_repo_id: Tanjid-code/Computer_vision
          huggingface_repo_id: Tanjid0/Computer_vison
          hf_token: ${{ secrets.HF_TOKEN }}
          repo_type: space
